name: Build

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: .

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Test with the dotnet CLI
        run: dotnet test --no-restore
  
  build-backend-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch,suffix=-{{ sha }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        env:
          CACHE_REPOSITORY: nilsharr/todoapp:buildcache
        uses: docker/build-push-action@v6
        with:   
          push: true
          file: src/ToDo.API/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.CACHE_REPOSITORY }}
          cache-to: type=registry,ref=${{ env.CACHE_REPOSITORY  }},mode=max